server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: ${CONTEXT_PATH:/}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092,127.0.0.1:9094,127.0.0.1:9096}
    consumer:
      group-id: jdmik12-${spring.application.name}-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: by.javaguru.jdmik12.common.*
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: ${spring.application.name:${random.uuid}}
  application:
    name: jdmik12-recruitment-service
  config:
    import: optional:file:.env.sample[.properties]
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/booking-db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    banner-mode: "off"

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
      tags:
        application: ${spring.application.name}
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}:${server.port}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true

integration:
  kafka:
    producer:
      security.topic.name: jdmik12.security.check.command
      notification.topic.name: jdmik12.notification.send.command
      outbox.topic.name: jdmik12.streaming.command
      dlt.topic.name: jdmik12.booking-pr.event.dlt
    consumer:
      booking.topic.name: jdmik12.booking-pr.event
    booking-command-topic:
      name: jdmik12.booking-pr.event
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2

scheduling:
  enabled: true

logging:
  level:
    root: INFO