apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-config
  namespace: jdmik12-rpynzar
data:
  CONTEXT_PATH: "/jdmik12-booking-service"
  LOGS_APPLICATION_LOKI_BASE_URL: "http://loki-stack-loki-distributed-gateway.observability:80"
  SPRING_PROFILES_ACTIVE: "loki"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://tempo.observability:4318/v1/traces"
  OTEL_SERVICE_NAME: "jdmik12-booking-service"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "jdmik12-booking-service"
  SERVER_PORT: "9097"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
